"""Main module for Okta API interactions."""

import requests
import os
from typing import Any

from services.service_token import get_service_token
from services.projects import get_projects_by_team
from services.resource_groups import get_resource_groups_by_team, get_projects_by_resource_group
from services.enrollment import generate_server_enrollment_token
import json


def main() -> None:
    """Main entry point for the script."""
    team_name = os.getenv("OKTA_TEAM")
    org_name = os.getenv("OKTA_ORG")
    target_project = os.getenv("OKTA_TARGET_PROJECT")
    if not team_name or not org_name:
        raise ValueError("TEAM_NAME and ORG_NAME environment variables must be set")

    # Get credentials from environment variables
    key_id = os.getenv("KEY_ID")
    key_secret = os.getenv("KEY_SECRET")

    if not key_id or not key_secret:
        raise ValueError("KEY_ID and KEY_SECRET environment variables must be set")

    try:
        data = get_service_token(team_name, org_name, key_id, key_secret)
        bearer_token = data["bearer_token"]
        print(f"Obtained bearer token: \n{bearer_token}\n")
        # print(data)
        dset = {}
        resource_groups = get_resource_groups_by_team(bearer_token, org_name, team_name)
        for rg in resource_groups:
            rgdset = {}
            print(rg)
            projects = get_projects_by_resource_group(bearer_token, org_name, team_name, rg["id"])
            rg["__projects"] = projects
        
        print(json.dumps(resource_groups, indent=2))
        
        et = generate_server_enrollment_token(
            team_name,
            target_project,
            org_name,
            bearer_token,
            description="Generated by script",
        )
        print(json.dumps(et, indent=2))
        
        # projects = get_projects_by_team(bearer_token, org_name, team_name)
        # print(projects)
    except requests.exceptions.RequestException as e:
        print(f"Error making API request: {e}")
    except ValueError as e:
        print(f"Configuration error: {e}")


if __name__ == "__main__":
    main()
